apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.application.namespace }}
data:
  create.sql: |
    CREATE USER payment_service WITH PASSWORD :PSWORD;
    CREATE DATABASE payment_db with owner payment_service;
