apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.application.namespace }}
data:
  create.sql: |
    CREATE USER delivery_service WITH PASSWORD :PSWORD;
    CREATE DATABASE delivery_db with owner delivery_service;
