host:
  name: arch.homework
application:
  namespace: development
  name: billing-service
  label: billing-service
  service:
    port: 80
  container:
    port: 8080
    env:
      - key: DB_HOST
        value: database-postgresql
      - key: DB_NAME
        value: billing_db
      - key: DB_USERNAME
        value: billing_service
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: kafka:9092
  replicaCount: 1
  image:
    repository: otuslearning/billing-service:0.0.1