apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.application.namespace }}
  name: "{{ .Values.application.name }}-svc"
  labels:
    app: {{ .Values.application.label }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.application.service.port }}
      targetPort: {{ .Values.application.container.port }}