apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.application.namespace }}
data:
  create.sql: |
    CREATE USER order_service WITH PASSWORD :PSWORD;
    CREATE DATABASE order_db with owner order_service;
