apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.application.namespace }}
data:
  create.sql: |
    CREATE USER billing_service WITH PASSWORD :PSWORD;
    CREATE DATABASE billing_db with owner billing_service;
