apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.application.namespace }}
data:
  create-password: {{ .Values.postgres.password }}
  password: {{ .Values.application.password }}