apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.application.namespace }}
data:
  create.sql: |
    CREATE USER auth_service WITH PASSWORD :PSWORD;
    CREATE DATABASE auth_db with owner auth_service;
