host:
  name: arch.homework
application:
  namespace: development
  name: order-service
  label: order-service
  service:
    port: 80
  container:
    port: 8080
    env:
      - key: DB_HOST
        value: database-postgresql
      - key: DB_NAME
        value: order_db
      - key: DB_USERNAME
        value: order_service
      - key: KAFKA_BOOTSTRAP_SERVERS
        value: kafka:9092
  replicaCount: 1
  image:
    repository: otuslearning/order-service:0.0.3