apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: {{ .Values.application.namespace }}
data:
  create.sql: |
    CREATE USER store_service WITH PASSWORD :PSWORD;
    CREATE DATABASE store_db with owner store_service;
